# Exercise on Functions
## Task 1
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
   
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_length(value, unit):
    """
    This function converts length measurements between meters and feet.
    The conversion depends on the unit provided ('m' for meters, 'ft' for feet).
    Returns the converted value as a float.
    """
    if unit == 'm':
        return value * 3.28084  # Convert meters to feet
    elif unit == 'ft':
        return value / 3.28084  # Convert feet to meters
    else:
        raise ValueError("Invalid unit for length conversion.")

def convert_weight(value, unit):
    """
    Converts weight measurements between kilograms and pounds.
    The function checks the unit and applies the relevant conversion.
    Returns the result as a float.
    """
    if unit == 'kg':
        return value * 2.20462  # Convert kg to lbs
    elif unit == 'lbs':
        return value / 2.20462  # Convert lbs to kg
    else:
        raise ValueError("Invalid unit for weight conversion.")

def convert_volume(value, unit):
    """
    Handles volume conversion between liters and gallons.
    Uses the provided unit to determine the appropriate calculation.
    Returns the converted volume as a float.
    """
    if unit == 'L':
        return value * 0.264172  # Convert liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Invalid unit for volume conversion.")

print("Unit Converter")
print("1. Length (meters <-> feet)")
print("2. Weight (kilograms <-> pounds)")
print("3. Volume (liters <-> gallons)")

try:
    choice = int(input("Choose conversion type (1-3): "))  # Ask user for conversion type
    value = float(input("Enter value to convert: "))  # Get value for conversion

    if choice == 1:
        unit = input("Enter unit ('m' for meters, 'ft' for feet): ").strip().lower()
        result = convert_length(value, unit)
    elif choice == 2:
        unit = input("Enter unit ('kg' for kilograms, 'lbs' for pounds): ").strip().lower()
        result = convert_weight(value, unit)
    elif choice == 3:
        unit = input("Enter unit ('L' for liters, 'gal' for gallons): ").strip().lower()
        result = convert_volume(value, unit)
    else:
        print("Invalid choice.")  # Handle incorrect selection

    print(f"Converted Value: {result:.2f}")  # Display the conversion result
except ValueError as e:
    print(f"Error: {e}")  # Handle invalid input values
except Exception:
    print("An unexpected error occurred.")  # General error handling


Unit Converter
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Choose conversion type (1-3): 2
Enter value to convert: 12
Enter unit ('kg' for kilograms, 'lbs' for pounds): kg
Converted Value: 26.46


## Task 2
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
   
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def compute_sum(values):
    """
    Computes the total sum of a list of numbers.
    Iterates through the list and accumulates the sum.
    Returns the final sum as a float.
    """
    total = 0
    for val in values:
        total += val
    return total

def compute_average(values):
    """
    Determines the average of a list of numbers.
    Utilizes the compute_sum function to get the total.
    Returns the calculated average.
    """
    total = compute_sum(values)
    return total / len(values)

def get_maximum(values):
    """
    Identifies the highest number in the given list.
    If the list is empty, returns None.
    Otherwise, iterates to find the max value.
    """
    if not values:
        return None
    max_num = values[0]
    for val in values:
        if val > max_num:
            max_num = val
    return max_num

def get_minimum(values):
    """
    Finds the lowest number in the list.
    If the list is empty, returns None.
    Otherwise, iterates to determine the minimum value.
    """
    if not values:
        return None
    min_num = values[0]
    for val in values:
        if val < min_num:
            min_num = val
    return min_num


print("Mathematical Operations on a List of Numbers")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    option = int(input("Select an operation (1-4): "))
    values = input("Enter numbers separated by spaces: ").split()
    values = [float(num) for num in values]  # Convert input into a list of float values

    if not values:
        raise ValueError("The list cannot be empty.")

    if option == 1:
        outcome = compute_sum(values)
        print(f"The total sum of the numbers is: {outcome:.2f}")
    elif option == 2:
        outcome = compute_average(values)
        print(f"The average of the numbers is: {outcome:.2f}")
    elif option == 3:
        outcome = get_maximum(values)
        print(f"The highest number in the list is: {outcome:.2f}")
    elif option == 4:
        outcome = get_minimum(values)
        print(f"The lowest number in the list is: {outcome:.2f}")
    else:
        print("Invalid selection.")

except ValueError as err:
    print(f"Error: {err}")  # Handles incorrect inputs
except Exception:
    print("An unexpected issue occurred.")  # General error handling


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Select an operation (1-4): 1
Enter numbers separated by spaces: 12
The total sum of the numbers is: 12.00


## List Manipulation
# Task 1
Write a Python function that extracts every other element from a list, starting from the first element.

### • Requirements:

– Define a function extract_every_other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def select_alternate_elements(data_list):
    """
    Retrieves every alternate element from a given list.
    Takes a list of numbers as input and returns a new list
    containing every second element starting from the first.
    """
    return data_list[::2]  # Uses slicing to pick alternate elements

test_list = [1, 2, 3, 4, 5, 6]
filtered_list = select_alternate_elements(test_list)

print("Modified list with alternate elements:", filtered_list)


Modified list with alternate elements: [1, 3, 5]


## Task 2
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

### • Requirements:

– Define a function get_sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
    new_list = []
    for i in range(start, end + 1):
        if 0 <= i < len(lst):
            new_list.append(lst[i])
    return new_list

sample_list = [1, 2, 3, 4, 5, 6]
start = int(input("Enter the start index: "))
end = int(input("Enter the end index: "))

new_list = get_sublist(sample_list, start, end)
print("The new list is:", new_list)


Enter the start index: 1
Enter the end index: 5
The new list is: [2, 3, 4, 5, 6]


## Task 3
Write a Python function that reverses a list using slicing.

### • Requirements:

– Define a function reverse_list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
    return lst[::-1]

sample_list = [1,2,3,4,5,6]
rev_list = reverse_list(sample_list)

print("Original list:", sample_list)
print("The reversed list is:", rev_list)

Original list: [1, 2, 3, 4, 5, 6]
The reversed list is: [6, 5, 4, 3, 2, 1]


## Task 4
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

### • Requirements:

– Define a function remove_first_last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    return lst[1:-1]

sample_list = [1,2,3,4,5,6]
result = remove_first_last(sample_list)

print("The new list is:", result)

The new list is: [2, 3, 4, 5]


## Task 5
Write a Python function that extracts the first n elements from a list.

### • Requirements:

– Define a function get_first_n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    return lst[:n]

num = int(input("Enter the number of elements:"))
sample_list = [1,2,3,4,5,6]

print("Result:", get_first_n(sample_list, num))

Enter the number of elements:4
Result: [1, 2, 3, 4]


## Task 6
Write a Python function that extracts the last n elements of a list using slicing.

### • Requirements:

– Define a function get_last_n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

num = int(input("Enter the number of elements:"))
sample_list = [1,2,3,4,5,6]

print("Result:", get_last_n(sample_list, num))

Enter the number of elements:12
Result: [1, 2, 3, 4, 5, 6]


## Task 7
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

### • Requirements:

– Define a function reverse_skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

sample_list = [1,2,3,4,5,6]
print("Result:", reverse_skip(sample_list))

Result: [5, 3, 1]


# Exercise on Nested Lists

## Task 1

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

### • Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
def flatten(lst):
    flat_list = []
    for i in lst:
        for j in i:
            flat_list.append(j)
    return flat_list

nested_list = [[1,2],[3,4],[5,6]]
print("Flattened list:", flatten(nested_list))

Flattened list: [1, 2, 3, 4, 5, 6]


## Task 2
Write a Python function that extracts a specific element from a nested list given its indices.

### • Requirements:

– Define a function access_nested_element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [11]:
def access_nested_element(lst, indices):
    element=lst
    for index in indices:
        element = element[index]

    return element

sample_list = [[1,2,3],[4,5,6],[7,8,9]]
indices = [2,1]

print("Result:", access_nested_element(sample_list, indices))


Result: 8


## Task 3

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

### • Requirements:

– Define a function sum_nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [12]:
def sum_nested(lst):
    sum = 0
    for num in lst:
        if isinstance(num, list):
            sum += sum_nested(num)
        elif isinstance(num, (int, float)):
            sum += num
    return sum

sample_list =  [[1, 2], [3, [4, 5]], 6]
result = sum_nested(sample_list)
print("The sum of elements is:", result)


The sum of elements is: 21


## Task 4

Write a Python function that removes all occurrences of a specific element from a nested list.

### • Requirements:

– Define a function remove_element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [13]:
def remove_element(lst, elm):
    new_lst=[]
    for num in lst:
        if isinstance(num, list):
            sub_list = remove_element(num, elm)
            if sub_list:
                new_lst.append(sub_list)
        elif num != elm:
            new_lst.append(num)
    return new_lst

sample_list =  [[1, 2], [3, 2], [4, 5]]
element = 2
print("New List:", remove_element(sample_list, element))

New List: [[1], [3], [4, 5]]


## Task 5
Write a Python function that finds the maximum element in a nested list (regardless of depth).

### • Requirements:

– Define a function find_max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
def find_max(lst):
    max_num = float(0)
    for num in lst:
        if isinstance(num, list):
            max_num = max(max_num, find_max(num))
        else:
            max_num = max(max_num, num)
    return max_num

sample_list = [[1, 2], [3, [4, 7]], 6]
print("The maximum number in the list is:", find_max(sample_list))

The maximum number in the list is: 7


## Task 6
Write a Python function that counts how many times a specific element appears in a nested list.

### • Requirements:

– Define a function count_occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [15]:
def count_occurences(lst, element):
    count = 0
    for num in lst:
        if isinstance(num, list):
            count += count_occurences(num, element)
        elif num == element:
            count += 1
    return count

sample_list =  [[1, 2], [2, 3], [2, 4]]
element = 2
print(f"The number of {element} in the list is:", count_occurences(sample_list, element))

The number of 2 in the list is: 3


## Task 7
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

### • Requirements:

– Define a function deep_flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [16]:
def deep_flatten(lst):
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.extend(deep_flatten(item))
        else:
            new_list.append(item)
    return new_list

sample_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("New flattened list is:", deep_flatten(sample_list))

New flattened list is: [1, 2, 3, 4, 5, 6, 7, 8]


## Task 8
Write a Python function that calculates the average of all elements in a nested list.

### • Requirements:

– Define a function average_nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
def average_nested(lst):
    def helper(current_list):
        total = 0.0
        count = 0
        for element in current_list:
            if isinstance(element, list):
                sub_total, sub_count = helper(element)
                total += sub_total
                count += sub_count
            elif isinstance(element, (int, float)) and not isinstance(element, bool):
                total += element
                count += 1
        return total, count

    total_sum, total_count = helper(lst)
    return total_sum / total_count if total_count != 0 else 0.0

sample_list = [[1, 2], [3, 4], [5, 6]]
print("The average is:", average_nested(sample_list))

The average is: 3.5


# Basic Vector and Matrix Operation with Numpy
## Problem 1: Array Creation

In [18]:
import numpy as np


## Problem 1.1
Initialize an empty array with size 2X2

In [19]:
arr = np.empty((2,2))
print("Empty array:", arr.astype(int))

Empty array: [[0 0]
 [0 0]]


## Problem 1.2
Initialize an all one array with size 4X2

In [20]:
arr = np.ones((4,2))
print("Ones array:", arr)

Ones array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Problem 1.3
Return a new array of given shape and type, filled with fill value.{Hint: np.full}

## Problem 1.4
Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [28]:
arr = np.array([[1,2],[3,4],[5,6]])
new_arr = np.zeros_like(arr)

print("Given array:\n", arr)
print("New array with zeros:\n", new_arr)

Given array:
 [[1 2]
 [3 4]
 [5 6]]
New array with zeros:
 [[0 0]
 [0 0]
 [0 0]]


## Problem 1.5
Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr = np.ones_like(arr)

print("Given array:\n",arr)
print("New array:\n", new_arr)

Given array:
 [[1 2 3 4]
 [5 6 7 8]]
New array:
 [[1 1 1 1]
 [1 1 1 1]]


## Problem 1.6
For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [29]:
new_list = [1,2,3,4]
arr = np.array(new_list)

print("Given list:\n", new_list)
print("Numpy array:\n", arr)

Given list:
 [1, 2, 3, 4]
Numpy array:
 [1 2 3 4]


## Problem 2: Array Manipulation, Nemuerical Ranges and Array Indexing
## Problem 2.1
Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [30]:
arr = np.arange(10, 50)

print("Array ranging from 10 to 49:", arr)

Array ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Problem 2.2
Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [31]:
arr = np.arange(0,9)
matrix = arr.reshape(3,3)

print("Array:\n",arr)
print("Matrix:\n", matrix)

Array:
 [0 1 2 3 4 5 6 7 8]
Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


## Problem 2.3
Create a 3X3 identity matrix.{Hint:np.eye()}

In [32]:
matrix = np.eye(3,3)
print("Identity Matrix:\n", matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Problem 2.4
Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [33]:
import random
arr = np.random.random(30)
mean = arr.mean()

print("Array:\n", arr)
print("Mean of the given array is: ", mean)

Array:
 [0.25552909 0.03079949 0.70046164 0.81893868 0.15637294 0.69473118
 0.48131314 0.70544982 0.05905349 0.09744959 0.51099043 0.89503662
 0.58532773 0.84747833 0.24173996 0.16373276 0.22310201 0.8343793
 0.81298633 0.30226274 0.02526794 0.76290785 0.13779016 0.41404306
 0.16342856 0.67107364 0.32345707 0.78607943 0.99618342 0.41548108]
Mean of the given array is:  0.47042824849070175


## Problem 2.5
Create a 10X10 array with random values and find the minimum and maximum values.


In [34]:
arr = np.random.randint(0,500,(10,10))
min_value = arr.min()
max_value = arr.max()

print("Random array:\n",arr)
print("Maximum value in the array is:", max_value)
print("Minimum value in the array is:", min_value)

Random array:
 [[494 237 420   1 284 422  88  45 340 474]
 [374 265 298 304 351 289 219 433 172 379]
 [383   4 198 416 429 328 398 353  65  70]
 [480 203 204 255 163 407 176 345 244 227]
 [472 212  66 409 448 348 355  24 236 252]
 [143  59 128 471 390 321 427 252 361 272]
 [361  52 258 116 416 179 311 253 402 210]
 [  3 267 266 156  56 148 407 123  52 207]
 [ 77 303 261 287  91 476 256  79 221 344]
 [318 210 327 116  82 271  30 148  65 215]]
Maximum value in the array is: 494
Minimum value in the array is: 1


## Problem 2.6
Create a zero array of size 10 and replace 5th element with 1.


In [35]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Problem 2.7
Reverse an array arr = [1,2,0,0,4,0].

In [36]:
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1]
print("Given array:\n",arr)
print("Reverse array:\n", rev_arr)

Given array:
 [1, 2, 0, 0, 4, 0]
Reverse array:
 [0, 4, 0, 0, 2, 1]


## Problem 2.8
Create a 2d array with 1 on border and 0 inside

In [37]:
rows = int(input("Enter the number of rows:"))
cols = int(input("ENter the number of collumns:"))

arr = np.ones((rows, cols), dtype=int)
arr[1:-1,1:-1] = 0

print("Array with 1 on border and 0 inside:\n",arr)

Enter the number of rows:1
ENter the number of collumns:2
Array with 1 on border and 0 inside:
 [[1 1]]


## Problem 2.9
Create a 8X8 matrix and fill it with a checkerboard pattern

In [38]:
matrix = np.zeros((8,8), dtype = int)
matrix[::2,::2] = 1
matrix[1::2, 1::2] = 1

print("Checkerboard pattern:\n", matrix)

Checkerboard pattern:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Problem 3: Array Operations

In [39]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

## Problem 3.1
Add two array

In [40]:
# addition of x and y
sum_1 = x+y
print("The sum of x and y is:", sum_1)

# addtion of v and w
sum_2 = v+w
print("The sum of v and w is:", sum_2)

The sum of x and y is: [[ 6  8]
 [10 13]]
The sum of v and w is: [20 22]


## Problem 3.2
Subtract the two array

In [41]:
# subtraction of x and y
diff_1 = x-y
print("The difference of x and y is:", diff_1)

# subtraction of v and w
diff_2 = v-w
print("The difference of v and w is:", diff_2)

The difference of x and y is: [[-4 -4]
 [-4 -3]]
The difference of v and w is: [-2 -2]


## Problem 3.3
Multiply the array with any integers of your choice

In [42]:
num = int(input("Enter a number of your choice"))

mul_x = x * num
print("Multiplication of array x:", mul_x)

mul_y = x * num
print("Multiplication of array y:", mul_y)

mul_v = v * num
print("Multiplication of array :", mul_v)

mul_w = w * num
print("Multiplication of array x:", mul_w)

Enter a number of your choice3
Multiplication of array x: [[ 3  6]
 [ 9 15]]
Multiplication of array y: [[ 3  6]
 [ 9 15]]
Multiplication of array : [27 30]
Multiplication of array x: [33 36]


## Problem 3.4
Find the squre of each element of the array

In [43]:
sq_x = x ** 2
print("Multiplication of array x:", sq_x)

sq_y = y ** 2
print("Multiplication of array y:", sq_y)

sq_v = np.square(v)
print("Multiplication of array v:", sq_v)

sq_w = np.square(w)
print("Multiplication of array w:", sq_w)

Multiplication of array x: [[ 1  4]
 [ 9 25]]
Multiplication of array y: [[25 36]
 [49 64]]
Multiplication of array v: [ 81 100]
Multiplication of array w: [121 144]


## Problem 3.5
FInd the dot product between: v and w, x and v, x and y

In [44]:
dot_vw = np.dot(v,w)
print("Dot product of v and w is:", dot_vw)

dot_xv = np.dot(x,v)
print("Dot product of x and v is:", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y is:", dot_xy)

Dot product of v and w is: 219
Dot product of x and v is: [29 77]
Dot product of x and y is: [[19 22]
 [50 58]]


## Problem 3.6
Concatenate x and y along row and concatenate v and w along column.

In [45]:
concatenate_xy = np.concatenate((x,y), axis = 0)
print("Concatenated x and y along row:", concatenate_xy)

concatenate_vw = np.vstack((v,w))
print("Concatenated v and w along column:", concatenate_vw)


Concatenated x and y along row: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along column: [[ 9 10]
 [11 12]]


## Problem 3.7
Concatenate x and v; if you get an error, observe and explain why did you get the error

In [46]:
try:
    np.concatenate((x,v))
except ValueError as e:
    error_msg = e
    print("Error concatenationg x and v:", error_msg)

Error concatenationg x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The x and v could not be concatenated because the dimension of both the matrix is different.

## Problem 4 : Matrix Operations

In [47]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

## Problem 4.1
### Prove A.A^(−1) = I

In [48]:
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("1. A.A^-1 = I:\n", I)
print("   Is close to identity matrix:", np.allclose(I, np.eye(2)))

1. A.A^-1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Is close to identity matrix: True


## Problem 4.2
### Prove AB != BA

In [49]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB != BA:", not np.array_equal(AB, BA))


2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB != BA: True


## Problem 4.3
### Prove (AB)^T = (B^T)*(A^T)

In [50]:
AB_transpose = np.transpose(AB)
B_tp_A_tp = np.dot(np.transpose(B), np.transpose(A))
equal = np.array_equal(AB_transpose, B_tp_A_tp)

print("(AB)^T == B^T * A^T", equal)

(AB)^T == B^T * A^T True


## Problem 4.4
Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

•Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [51]:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

A_eq_inv = np.linalg.inv(A_eq)
result = np.dot(A_eq_inv, B_eq)

print("Solution  the system of equation is:", result)

Solution  the system of equation is: [ 2.  1. -2.]


## Experiment

## Element wise Addition

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [52]:
import time

def list_addition(list1, list2):
    result = []
    for i in range(len(list1)):
        result.append(list1[i]+list2[i])
    return result

def array_addition(arr1, arr2):
    return arr1 + arr2

size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_addition(list1, list2)
list_end_time = time.time()
list_time = list_end_time-list_start_time

array1 = np.arange(size)
array2 = np.arange(size)
arr_start_time = time.time()
arr_result = array_addition(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:.6f} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

Time taken by list: 0.088486 seconds
Time taken by array: 0.004748 seconds


## Element wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [53]:
def list_multiplication(list1, list2):
    result = []
    for i in range(len(list1)):
        result.append(list1[i]*list2[i])
    return result

def array_multiplication(arr1, arr2):
    return arr1 * arr2

size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_multiplication(list1, list2)
list_end_time = time.time()
list_time = list_end_time-list_start_time

array1 = np.arange(size)
array2 = np.arange(size)
arr_start_time = time.time()
arr_result = array_multiplication(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:.6f} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

Time taken by list: 0.088371 seconds
Time taken by array: 0.005433 seconds


## Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [54]:
def list_dotproduct(list1, list2):
    dp_list = 0
    for i in range(len(list1)):
        dp_list += list1[i] * list2[i]
    return dp_list

def array_dotproduct(arr1, arr2):
    return np.dot(arr1, arr2)

size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_dotproduct(list1, list2)
list_end_time = time.time()
list_time = list_end_time-list_start_time

array1 = np.arange(size)
array2 = np.arange(size)
arr_start_time = time.time()
arr_result = array_dotproduct(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:.6f} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

Time taken by list: 0.114374 seconds
Time taken by array: 0.001368 seconds


## Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
def list_matrix_mul(mat1, mat2):
    result = [[0 for _ in range(size)] for _ in range(size)]
    for i in range(size):
        for j in range(size):
            for k in range(size):
                result[i][j] += mat1[i][k] * mat2[k][j]

    return result

def numpy_matrix_mul(mat1, mat2):
    return np.matmul(mat1, mat2)

size = 1000

matrix1 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]


list_start_time = time.time()
list_mul = list_matrix_mul(matrix1, matrix2)
list_end_time = time.time()
list_time = list_end_time - list_start_time

numpy_start_time = time.time()
np_mul = numpy_matrix_mul(matrix1, matrix2)
numpy_end_time = time.time()
np_time = numpy_end_time - numpy_start_time


print(f"Time for list matrix multiplication is:{list_time:.6f} seconds")
print(f"Time for numpy matrix multiplication is:{np_time:.6f} seconds")



Time for list matrix multiplication is:145.472615 seconds
Time for numpy matrix multiplication is:2.232152 seconds
